### ISSUE TITLE
NameBits question

### ISSUE THREAD

**Issue by ret** [mn416/blarney#51]
Q: I was hoping to use the [NamBits example](https://github.com/mn416/blarney/commit/2854ca924ee620c374bdd95839abefd92bb8304c#diff-c7c05452061300ebe7aab59607632274) to influence signal names to simplify debugging `.vcd` files. Unfortunately, the `"AAA"` and `"BBB"` strings used in the example do not show up in the `top.v` file. 

Is this intentional? Is there maybe an option I need to enable to influence the signal naming via hints.

**Comment by gameboo** [comment]
Hi @ret,

This is not intentional indeed, as the desired behaviour is the one you'd expect :). We are aware of this not currently being in a working state and are looking into it. There is a separate branch to handle names and try to infer good ones automatically, which is where most ongoing work on naming is happening. Hopefully, we'll converge on a stable, working solution soon.

Thank you for your comment!

**Comment by gameboo** [comment]
Hi again @ret,

For what it is worth, I forgot to mention this last time, but we find using `display` gets us quite a long way when it comes to debugging. Maybe this approach can be of some help to you on top of using `.vcd`?
In any case, commit 86ffc6c3707724af0e6230ba675b89bdfb66841d should help you out (it should let things behave the way they should as far as names are concerned).
As previously mentioned, we hope to provide some more features relating to naming eventually, so keep an eye out, maybe useful things will pop up.

I'll close the issue now. Do reopen it if you think we've missed something relevant there.
Thanks again!
